// GENERATED — do not edit.
// Source: 30_ENGINE/pvm/taxonomy.py
// Regenerate: python 40_APP/generate_shared.py
//
// The engine is the reference implementation and the app is what ships. Maintained by
// hand these two diverge silently: the app files a passport somewhere the engine would
// not, and every number measured on the engine stops describing the product. CI
// regenerates this and fails on any diff.

import Foundation

public enum Taxonomy {
    public static let separator = " > "

    public static let roots: [String] = [
        "Documents",
        "People",
        "Screenshots",
        "Places",
        "Travel",
        "Objects",
        "Purchases",
        "Clothing",
        "Work",
        "Downloads",
        "Timeline",
    ]

    /// Every node the tree ships with. A rule may not name anything else.
    public static let allNodes: Set<String> = [
        "Documents",
        "Documents > Identity",
        "Documents > Identity > ID Cards",
        "Documents > Identity > Passports",
        "Documents > Identity > Driver Licenses",
        "Documents > Identity > Visas",
        "Documents > Contracts",
        "Documents > Contracts > Tenancy",
        "Documents > Contracts > Employment",
        "Documents > Contracts > Insurance",
        "Documents > Contracts > Other",
        "Documents > Financial",
        "Documents > Financial > Bank",
        "Documents > Financial > Tax",
        "Documents > Financial > Statements",
        "Documents > Receipts",
        "Documents > Warranty",
        "Documents > Medical",
        "Documents > Other Documents",
        "People",
        "People > Anna",
        "People > Ben",
        "People > Chris",
        "People > Dana",
        "People > Groups",
        "Screenshots",
        "Screenshots > Chat",
        "Screenshots > Shopping",
        "Screenshots > Maps",
        "Screenshots > Web",
        "Screenshots > Work",
        "Screenshots > Temporary",
        "Screenshots > Temporary > Verification Codes",
        "Screenshots > Temporary > Pickup Codes",
        "Screenshots > Temporary > Tickets",
        "Screenshots > Errors",
        "Places",
        "Places > United Kingdom",
        "Places > United Kingdom > London",
        "Places > United Kingdom > Brighton",
        "Places > Japan",
        "Places > Japan > Tokyo",
        "Travel",
        "Travel > Tokyo · Apr 2025",
        "Travel > Brighton · Aug 2024",
        "Travel > Lisbon · Sep 2023",
        "Objects",
        "Objects > Bicycle",
        "Objects > Appliances",
        "Objects > Devices",
        "Objects > Furniture",
        "Objects > Other",
        "Purchases",
        "Purchases > Receipts",
        "Purchases > Orders",
        "Purchases > Warranty",
        "Purchases > Delivery",
        "Clothing",
        "Clothing > Tops",
        "Clothing > Outerwear",
        "Clothing > Shoes",
        "Clothing > Other",
        "Work",
        "Work > Whiteboards",
        "Work > Meetings",
        "Work > Documents",
        "Work > Other",
        "Downloads",
        "Downloads > Memes",
        "Downloads > Wallpapers",
        "Downloads > Social",
        "Timeline",
        "Timeline > 2026",
        "Timeline > 2025",
        "Timeline > 2024",
        "Timeline > 2023",
        "Timeline > 2022",
    ]

    public static let leaves: Set<String> = [
        "Documents > Identity > ID Cards",
        "Documents > Identity > Passports",
        "Documents > Identity > Driver Licenses",
        "Documents > Identity > Visas",
        "Documents > Contracts > Tenancy",
        "Documents > Contracts > Employment",
        "Documents > Contracts > Insurance",
        "Documents > Contracts > Other",
        "Documents > Financial > Bank",
        "Documents > Financial > Tax",
        "Documents > Financial > Statements",
        "Documents > Receipts",
        "Documents > Warranty",
        "Documents > Medical",
        "Documents > Other Documents",
        "People > Anna",
        "People > Ben",
        "People > Chris",
        "People > Dana",
        "People > Groups",
        "Screenshots > Chat",
        "Screenshots > Shopping",
        "Screenshots > Maps",
        "Screenshots > Web",
        "Screenshots > Work",
        "Screenshots > Temporary > Verification Codes",
        "Screenshots > Temporary > Pickup Codes",
        "Screenshots > Temporary > Tickets",
        "Screenshots > Errors",
        "Places > United Kingdom > London",
        "Places > United Kingdom > Brighton",
        "Places > Japan > Tokyo",
        "Travel > Tokyo · Apr 2025",
        "Travel > Brighton · Aug 2024",
        "Travel > Lisbon · Sep 2023",
        "Objects > Bicycle",
        "Objects > Appliances",
        "Objects > Devices",
        "Objects > Furniture",
        "Objects > Other",
        "Purchases > Receipts",
        "Purchases > Orders",
        "Purchases > Warranty",
        "Purchases > Delivery",
        "Clothing > Tops",
        "Clothing > Outerwear",
        "Clothing > Shoes",
        "Clothing > Other",
        "Work > Whiteboards",
        "Work > Meetings",
        "Work > Documents",
        "Work > Other",
        "Downloads > Memes",
        "Downloads > Wallpapers",
        "Downloads > Social",
        "Timeline > 2026",
        "Timeline > 2025",
        "Timeline > 2024",
        "Timeline > 2023",
        "Timeline > 2022",
    ]

    /// Branches grown from the user's own library — a named face, a
    /// country nobody predicted, a year that had not happened yet.
    public static let extensibleRoots: Set<String> = [
        "People",
        "Places",
        "Timeline",
        "Travel",
    ]

    /// `_also_in`: the same asset under two entries, one original (§3).
    public static let crossListing: [String: String] = [
        "Documents > Receipts": "Purchases > Receipts",
        "Documents > Warranty": "Purchases > Warranty",
        "Purchases > Receipts": "Documents > Receipts",
        "Purchases > Warranty": "Documents > Warranty",
    ]
}
