#!/usr/bin/env python3
"""Generate the in-app legal text from the published Markdown.

The privacy policy and the terms exist twice: as the documents the Owner publishes at
the two URLs App Store Connect requires, and as screens inside the app. Two copies of a
legal text drift, and the drift is invisible — nobody diffs a Swift string literal
against a web page. So the Markdown is the source and the Swift file is generated, the
same arrangement `generate_shared.py` already uses for the taxonomy and the rules.

The app carries the text rather than fetching it because the app has no code for fetching
anything. A privacy policy that is only reachable online, in an app whose claim is that it
sends nothing anywhere, is unreadable exactly when someone is trying to check the claim.

Usage:
    python3 40_APP/generate_legal.py            # write the Swift file
    python3 40_APP/generate_legal.py --check    # fail if it is out of date
    python3 40_APP/generate_legal.py --selftest
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "40_APP" / "PVM" / "Support" / "LegalText.generated.swift"

SOURCES = [
    ("privacyPolicy", ROOT / "50_LAUNCH" / "PRIVACY_POLICY.md"),
    ("termsOfService", ROOT / "50_LAUNCH" / "TERMS_OF_SERVICE.md"),
]

# Blockquotes in these documents are notes to the Owner about the document itself
# ("这是一份草案", "待 Owner 填写 …"). They belong in the repository and not on a screen
# a user reads, so they are the one thing stripped on the way in.
NOTE = re.compile(r"^\s*>")

PLACEHOLDER = re.compile(r"待 ?Owner ?填写|待定")


def body(path: pathlib.Path) -> str:
    kept = [line for line in path.read_text(encoding="utf-8").splitlines()
            if not NOTE.match(line)]
    text = "\n".join(kept)
    text = re.sub(r"\n{3,}", "\n\n", text).strip()
    return text + "\n"


def render(bodies: dict[str, str]) -> str:
    out = [
        "// GENERATED by 40_APP/generate_legal.py from 50_LAUNCH/*.md — do not edit.",
        "//",
        "// The published documents are the source. `verify.sh` regenerates this file and",
        "// fails if it differs, so the text on the screen and the text at the URL cannot",
        "// drift apart without someone noticing.",
        "",
        "enum LegalText {",
    ]
    for name, text in bodies.items():
        out.append(f"    static let {name} = #\"\"\"")
        out.append(text.rstrip("\n"))
        # The closing delimiter sits at column 0. Swift strips from every line of a
        # multi-line literal exactly the indentation of its closing delimiter, so an
        # indented `"""#` over unindented Markdown is "insufficient indentation of the
        # next N lines" — a compile error, and the one this generator hit first.
        out.append('"""#')
        out.append("")
    out.append("}")
    return "\n".join(out).rstrip("\n") + "\n"


def build() -> str:
    return render({name: body(path) for name, path in SOURCES})


def selftest() -> int:
    import tempfile
    with tempfile.TemporaryDirectory() as directory:
        sample = pathlib.Path(directory) / "s.md"
        sample.write_text("# T\n\n> a note to the Owner\n\nreal text\n", encoding="utf-8")
        got = body(sample)
        assert "a note to the Owner" not in got, got
        assert "real text" in got, got
        assert got.startswith("# T"), got
    rendered = render({"x": "line\n"})
    assert 'static let x = #"""' in rendered, rendered
    assert rendered.rstrip().endswith("}"), rendered
    # Swift strips from every line of a multi-line literal exactly the indentation of
    # the CLOSING delimiter. An indented `"""#` over unindented Markdown is a compile
    # error, and it is the first thing this generator got wrong.
    assert '\n"""#\n' in rendered, "closing delimiter must sit at column 0"
    print("generate_legal selftest: ok")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--selftest", action="store_true")
    args = parser.parse_args()
    if args.selftest:
        return selftest()

    for _, path in SOURCES:
        if not path.exists():
            print(f"missing source document: {path}", file=sys.stderr)
            return 1

    generated = build()
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != generated:
            print(f"{OUT.relative_to(ROOT)} is out of date — "
                  "run: python3 40_APP/generate_legal.py", file=sys.stderr)
            return 1
        print(f"{OUT.relative_to(ROOT)} matches 50_LAUNCH/*.md")
    else:
        OUT.write_text(generated, encoding="utf-8")
        print(f"wrote {OUT.relative_to(ROOT)} ({len(generated)} bytes)")

    # A warning, not a failure. The placeholders are real and the Owner has to fill
    # them before submission, but a half-written policy in the repository is a normal
    # state and blocking every build on it would just get the check disabled.
    unresolved = {path.name: len(PLACEHOLDER.findall(path.read_text(encoding="utf-8")))
                  for _, path in SOURCES}
    outstanding = {k: v for k, v in unresolved.items() if v}
    if outstanding:
        print("NOTE — placeholders still to be filled before submission: "
              + ", ".join(f"{k}: {v}" for k, v in outstanding.items()))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
